spring:
  profiles:
    active: local
---
server:
  port: 3006
  forward-headers-strategy: native

analytics:
  export:
    local-path: ./tmp
    retention-months: 2


# JWT 설정 추가
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-in-milliseconds: 3600000 # 1시간
  refresh-token-expiration-in-milliseconds: 604800000 # 7일