spring:
  profiles:
    active: prod
---
server:
  port: 3006
  forward-headers-strategy: native

analytics:
  export:
    local-path: ./tmp
    retention-months: 2
    s3-bucket: ${S3_BUCKET}
    s3-key-prefix: exports/daily


# JWT 설정 추가
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-in-milliseconds: 3600000 # 1시간
  refresh-token-expiration-in-milliseconds: 604800000 # 7일


cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false