spring:
  profiles:
    active: local
---
server:
  port: 3006
  forward-headers-strategy: native

analytics:
  export:
    local-path: ./tmp
    retention-months: 2
    s3-bucket: ${S3_BUCKET} # 분석 데이터가 쌓이는 버킷
    s3-key-prefix: exports/daily


# JWT 설정 추가
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-in-milliseconds: ${JWT_ACCESS_EXPIRATION} # 1시간
  refresh-token-expiration-in-milliseconds: ${JWT_REFRESH_EXPIRATION} # 7일


cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET} # 기본 스토리지 버킷
      logo:
        bucket: ${S3_LOGO_BUCKET}
        baseurl: ${S3_LOGO_BASEURL}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false