spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: ${LOCAL_DB_URL}

    username: ${LOCAL_DB_USERNAME}

    password: ${LOCAL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # 로컬 테스트 환경에서는 'create', 'update' 등을 고려
    show-sql: true
    properties:
      hibernate:
        format_sql: true


analytics:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${READONLY_LOCAL_DB_URL}
    username: ${READONLY_LOCAL_DB_USER}
    password: ${READONLY_LOCAL_DB_PW}

